name: Sync

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allows manual triggering

jobs:
  update-tree:
    runs-on: ubuntu-latest
    env:
      HUGGINGFACE_REPO: "https://huggingface.co/mathewb20121/test"
      CLOUDFLARE_KV_URL: "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/storage/kv/namespaces/${{ secrets.CF_KV_NAMESPACE_ID }}/values/tree"
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Clone HF repo (without LFS files)
        run: |
          GIT_LFS_SKIP_SMUDGE=1 git clone --depth=1 "$HUGGINGFACE_REPO" repo

      - name: Build file tree
        run: |
          cd repo
          find . -type f | sed 's|^\./||' | jq -R . | jq -s . > tree.json

      - name: Upload to Cloudflare KV
        run: |
          curl -X PUT "$CLOUDFLARE_KV_URL" \
            -H "Authorization: Bearer $CF_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data-binary @repo/tree.json
